FROM ubuntu:14.04

RUN apt-get update && apt-get install -y firefox

# Replace !!REPLACE_*!! with your user / group id
# See the build.sh script
RUN export uid=!!REPLACE_UID!! gid=!!REPLACE_GID!! && \
    mkdir -p /home/developer && \
    echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown ${uid}:${gid} -R /home/developer

USER developer
ENV HOME /home/developer
CMD /usr/bin/firefox
